# Dockerfile para desarrollo

FROM node:20-alpine

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    git \
    curl \
    bash

RUN npm install -g @ionic/cli cordova

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200
EXPOSE 8100
EXPOSE 35729

CMD ["npm", "start"]

